### ISSUE TITLE
Compiling for AutoCAD 2021?

### ISSUE THREAD

**Issue by truevis** [dalefugier/DOSLib#1]
What will we have to do to make an ARX that works with AutoCAD 2021? We can get both the AutoCAD 2021 beta and ObjectARX SDK from https://feedback.autodesk.com/
![image](https://user-images.githubusercontent.com/3574046/73574730-0870e680-44a9-11ea-9cfb-0e76d0f9517e.png)

**Comment by dalefugier** [comment]
The next version of AutoCAD is a binary breaking release. Since I don't support pre-releases, you have two options: 1.) clone the repository, and modify and build project against the next ObjectARX SDK yourself, or 2.) wait for the next version of AutoCAD to released, at which time I will to 1.).

**Comment by truevis** [comment]
>... Since I don't support pre-releases, you have two options: 1.) clone the repository, and modify and build project against the next ObjectARX SDK yourself, or 2.) wait for the next version of AutoCAD to released, at which time I will to 1.).

Good news! Are there instructions anywhere on how to compile the DOSLib src into an ARX with Visual Studio 2017 and AutoCAD 2020?

**Comment by dalefugier** [comment]
I've updated the source to support AutoCAD 2021. You can find a pre-built binary in under Releases.
