### ISSUE TITLE
Suggestion: Reuse last position of dialogues

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [dalefugier/DOSLib#13]
If this is not the correct place for suggestions please let me know.
xxx
It seems that all the dialogues (esp. the message boxes) appears always centred, not using the last position where they were closed before. Is there a change to reuse the last position? Or will it be implemented sometimes?

**Comment by dalefugier** [comment]
Hi @Pierre-de-la-Verre,

You are welcome to drop wishes here.

DOSLib dialog boxes that inherit from `CAcUiDialog` will remember their last positions. I don't recall if all the message boxes (there are more than one) use a custom dialog or just hack into the Windows message box.

-- Dale

**Comment by Pierre-de-la-Verre** [comment]
Hi @dalefugier 

thanks for reply,but now I don't know - will there be changed something or can the user do some special tricks?

**Comment by dalefugier** [comment]
Hi @Pierre-de-la-Verre,

DOSLib is open-source. So if you want to fix this  yourself, you can clone the project, make a branch, change the code, and submit a pull request. Otherwise, I'll try to remember to have a look at this the next time I'm in the code.

Thanks,

-- Dale

**Comment by Pierre-de-la-Verre** [comment]
Thanks Dale
my coding competence would not really improve this project ;-)
For me it is OK this way, it is no high-level priority ..
