### ISSUE TITLE
dos_getreal: wrong(?) message for minimum value and no maximum

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [dalefugier/DOSLib#15]
The syntax for dos_getreal is:
`(dos_getreal title prompt [flags [default [max [min]]]])`

So I used:
`(dos_getreal "3bo" (strcat "Wunschradius (>" (rtos minrad) ") eingeben: ") 7 0 50000 3.8))`
or
`(dos_getreal "3bo" (strcat "Wunschradius (>" (rtos minrad) ") eingeben: ") 7 0 50000 minrad))`

Problem a:
When I enter a value like "3" - which is under the minimum of 3.8 - I get a message "Please enter a real number greater than or equal to 4". The message is (nearly) correct, but it demands the wrong minimum value

Problem / Question b:
How to define a parameter that I don't have a "max-value"? Nil or t are not accepted ..

**Comment by dalefugier** [comment]
This will be fixed in the next release.
