### ISSUE TITLE
Autocad 2021 Load problems

### ISSUE THREAD

**Issue by DuncanHallam** [dalefugier/DOSLib#20]
Hi,

I'm trying to load the latest version to AutoCAD 2021 but it just keeps coming up with unable to load.

Any help would be great because we use the dos clipboard in one of our lisp.

Duncan

**Comment by dalefugier** [comment]
Hi @DuncanHallam,

Make sure to load `DOSLib24x64.arx`.

https://github.com/dalefugier/DOSLib/wiki/Introduction#autocad-files

-- Dale
