### ISSUE TITLE
dos_listbox does not handle nil

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [dalefugier/DOSLib#24]
Suggestion - error handling:

This is the example from help-file and works fine:
`(dos_listbox "Set Current Layer" "Select a layer" '("Layer1" "Layer2" "Layer3"))`

With nil as member of the list the commands ends with nil (also as described  ..)
`(dos_listbox "Set Current Layer" "Select a layer" '("Layer1" nil "Layer2" "Layer3"))`

Of course this issue could be checked and handled before feeding it to dos_listbox, but nevertheless a better error_handling would be fine.

**Comment by dalefugier** [comment]
Just do this:
```
(vl-remove nil '("Layer1" nil "Layer2" "Layer3"))
```
