### ISSUE TITLE
dos_combolist: dialogue has fixed height

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [dalefugier/DOSLib#27]
In dos_combolist, I can change the width. but not the height of the dialogue, although the "mouse double arrow" is displayed for all sides.
Bug or feature?

**Comment by dalefugier** [comment]
Looks like a feature.

https://github.com/dalefugier/DOSLib/blob/27acd54012b7f580372a326f8c2715ae3c2402cd/source/DosComboListDialog.cpp#L101
