### ISSUE TITLE
doslib for AutoCAD LT 2024

### ISSUE THREAD

**Issue by gorthaurswiss** [dalefugier/DOSLib#30]
hello

new in autocad lt 2024 it is possible to load lisp etc..
unfortunately it is not possible to load arx files.

would it be possible to compile doslib in vlx or fas?

thanks a lot
cedi

**Comment by dalefugier** [comment]
Hi @gorthaurswiss,

No, this is not possible - sorry.

AutoCAD LT does not load .arx apps - this is by design.

-- Dale

**Comment by gorthaurswiss** [comment]
hi @dalefugier 

thank you for the quick reply.
but you have seen that autocad LT 2024 new can also load LISP,VLX and FAS?

greetings cedi
