### ISSUE TITLE
dos_progbar doesn't count "relative"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [dalefugier/DOSLib#32]
DosLib 9.0.3 on Autocad Map3D 2023 German Win 10

I took the examples from the helpfile and made this small loop.
If I understand correctly it should set the value for prog_bar to 10 and then counts back to 0.
But I see the full prog_bar, see counting the loops, and finally the progbar is erased.

Using absolute value works fine.
What's wrong here?

```
(defun c:checkdosprogbar ( )
    (setq counter 0)
    (dos_progbar "Wait..." 10)
    (dos_pause 3)
    (repeat 10
        (princ (strcat "\nCounter: " (itoa (setq counter (1+ counter)))))
        (dos_pause 3)
        (dos_progbar -1)
    )
    (dos_progbar)
    (princ)
)
```

**Comment by dalefugier** [comment]
Call this with a positive value within the range specified to set the current position of the status bar. Pass a negative number to add an amount to the current position (relative).

**Comment by Pierre-de-la-Verre** [comment]
Sorry, but I don't understand. What will be the right code from above to count from 0 to 10?

**Comment by dalefugier** [comment]
This seems to work:
```
(defun c:dosbar ( )
    (setq counter 0)
    (dos_progbar "Wait..." 10)
    (dos_pause 3)
    (repeat 10
        (princ (strcat "\nCounter: " (itoa (setq counter (1+ counter)))))
        (dos_pause 1)
	(dos_progbar counter)
    )
    (dos_progbar)
    (princ)
)
```

**Comment by Pierre-de-la-Verre** [comment]
Yes, that's the "absolute" version, when I understand it correctly.
Thanks.
