### ISSUE TITLE
dos_closeall does nothing ..

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [dalefugier/DOSLib#33]
Autocad Map 3D 2023 German, 2023.0.3 Update, DosLib 9.0.3
Bricscad 23 German
When I call (doc_closeall), it hangs / stops with the command "_.close" and does nothing

![dos_closeall](https://github.com/dalefugier/DOSLib/assets/13277944/3c4285b3-643d-4b6a-905e-d834d5ef3652)

Some ideas about this behaviour?

**Comment by dalefugier** [comment]
Fixed - https://github.com/dalefugier/DOSLib/releases/tag/2024.03.28

**Comment by dalefugier** [comment]
Fixed - https://github.com/dalefugier/DOSLib/releases/tag/2024.03.28
