### ISSUE TITLE
dos_strreplace: problems with oldchars = newchars

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [dalefugier/DOSLib#34]
Autocad Map 3D 2023 German, 2023.0.3 Update, DosLib 9.0.3
Bricscad V23
--------------------
Using (unintended) the same strings for old- and newchars leads to an endless loop, Acad has to be shut down ..

```
Befehl: (dos_strreplace "12345" "3" "6" t)
"12645"

Befehl: (dos_strreplace "12345" "3" "5" t)
"12545"

Befehl: (dos_strreplace "12345" "5" "5" t)
--> Acad with no reaction and full CPU-load
```

**Comment by dalefugier** [comment]
Fixed - https://github.com/dalefugier/DOSLib/releases/tag/2024.03.28
