### ISSUE TITLE
Doslib for BricsCAD v25

### ISSUE THREAD

**Issue by CertHaramas** [dalefugier/DOSLib#38]
Hello,
as the BricsCAD v25 is about to be released (there is already v25.0 (beta) out including proper SDK), could also doslib for BricsCAD v25 be compiled and released?
Best regards,
Lukas

**Comment by CertHaramas** [comment]
Hello, just to inform you - the official version BricsCAD v25.1.05 has been released.

**Comment by dalefugier** [comment]
https://github.com/dalefugier/DOSLib/releases/tag/2024.10.18
