### ISSUE TITLE
Requirement for Unite Test cases

### ISSUE THREAD

**Issue by ArphonePei** [dalefugier/DOSLib#5]
I have mirgated the project to ZWCAD, so is it possible to have some test cases for unit test?
Besides, may I submit a pull request to merge my changes?

**Comment by dalefugier** [comment]
Hi @ArphonePei, I don't have test cases. Keep in mind DOSLib has been available for 28 years. So if you search some of the more popular AutoLISP sites, you'll find numerous examples of its usage. And, sure, feel free to submit a PR.

-- Dale

**Comment by ArphonePei** [comment]
Thank you, I will submit a PR after finishing some basic test.
